### ISSUE TITLE
No matching distribution found for djangoshop-paypal==0.2.0

### ISSUE THREAD

**Issue by maltitco** [awesto/djangoshop-paypal#2]
From consol:
pip install djangoshop-paypal==0.2.0
Collecting djangoshop-paypal==0.2.0
  Could not find a version that satisfies the requirement djangoshop-paypal==0.2.0 (from versions: 0.1.0, 0.1.3, 0.1.4)
No matching distribution found for djangoshop-paypal==0.2.0

**Comment by jrief** [comment]
Thanks for reporting.
Just uploaded to PyPI
