### ISSUE TITLE
SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by maltitco** [awesto/djangoshop-paypal#3]
When trying to pay through paypal I have an error:

requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)
[2017-05-10 13:46:53,795 basehttp] ERROR: "POST /angular/reverse/?djng_url_name=shop%3Acheckout-purchase HTTP/1.1" 500 9404

**Comment by maltitco** [comment]
After installing the latest version of the requests, problem do not exist.
Jacob please update the requirements.txt file - if it possible.

PayPal Test payments work correctly.

**Comment by jrief** [comment]
Could you please retest if the latest commit from GitHub works for you.
I then will release 0.2.1

**Comment by maltitco** [comment]
Hi Jacob, yes it works for me.
