### ISSUE TITLE
Cancel payment return: Page not found (404)

### ISSUE THREAD

**Issue by maltitco** [awesto/djangoshop-paypal#4]
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/en/page__cancel-payment__not-found-in-cms/
Raised by:	cms.views.details

The current URL, /en/page__cancel-payment__not-found-in-cms/, didn't match any of these.

**Comment by jrief** [comment]
have a look at ``PayPalPayment.cancel_view``:

You must add page to the CMS with the id ``cancel-payment``

**Comment by maltitco** [comment]
I just found this information in code.
Please put this information to the readme file.

**Comment by jrief** [comment]
for consistency, I used another reverse name.
please review
